### ISSUE TITLE
Fixed Crash For New Version,Try.

### ISSUE THREAD

**Issue by ohyeah521** [wanam/YouTubeAdAway#110]
@wanam 
First of all, thank you for your work, I am using some of your code and borrowing your thoughts. 
Due to the new version of YouTube, the project code is no longer working properly. Therefore, after reverse analysis, I re-implemented the function of advertising. I also remove the advertisement during the video playback. The code is not open source for the time being, so as not to be targeted by Google. 
If you have any questions about open source agreements or other issues, please contact me, my email is: 977792 [@]gmail.com
------------------------------------------------------------

Download myapk, try this:
https://github.com/ohyeah521/NoAds-For-YouTube/releases

**Comment by rambomhtri** [comment]
Working like a charm in Oreo 8.1.0 using YouTube 14.18.56. Thanks!

What do you mean by "I did not remove the advertisement during the video playback". I'm not getting any kind of ads, no static, nor in-video game, nothing.

**Comment by ohyeah521** [comment]
@rambomhtri  Wrong, I mean, this plugin supports the removal of dynamic ads during video playback.

**Comment by rambomhtri** [comment]
> @rambomhtri Wrong, I mean, this plugin supports the removal of dynamic ads during video playback.

I don't think you understood. I've also installed the YouTube Background playback, which lets you switch to another app or lock the phone while a video is playing, and the video won't stop. Well, background playback, it's quite self-defining. After the installation of your apk, whenever I "minimize" YouTube or lock the phone, the video stops, so basically background playback doesn't work since I installed your app.
